- name: "Download node exproter"
  become: True
  shell:
    cmd: "wget https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz; mv node_exporter-0.17.0.linux-amd64.tar.gz /tmp"
    chdir: .


- name: "move node exproter"
  become: True
  shell:
    cmd: "ls"
